name: Validate TTL Files

on: [push] 

jobs:
  validate-ttl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Find and process .ttl files
      run: |
        find . -type f -name '*.ttl' | while read file; do
          # Adjust the file path to remove the './' part
          adjusted_file_path=$(echo "$file" | sed 's|^./||')  
          echo "Processing $adjusted_file_path with Docker..."
          docker run --rm -v "$file:/data/$adjusted_file_path" skohub/jena:4.6.1 "shacl validate --shapes https://raw.githubusercontent.com/skohub-io/shapes/main/skohub.shacl.ttl --data /data/$adjusted_file_path"
        done

